[project]
name = "dokuWikiDumper"
version = "0.2.6"
description = "A tool for archiving DokuWiki"
authors = [
    {name = "yzqzss", email = "yzqzss@saveweb.org"},
]
license = "GPL-3.0-or-later"
license-files = ["LICENSE.md"]
requires-python = "<4.0,>=3.10"
dependencies = [
    "requests>=2.33.0,<3.0.0",
    "beautifulsoup4<5.0.0,>=4.13.4",
    "internetarchive<6.0.0,>=5.4.0",
    "rich<15.0.0,>=14.0.0",
    "python-slugify<9.0.0,>=8.0.4",
    "typing-extensions<5.0.0,>=4.13.2",
    "lxml>=6.0.2",
]
readme = "README.md"

[project.urls]
"Bug Tracker" = "https://github.com/saveweb/dokuwiki-dumper/issues"
repository = "https://github.com/saveweb/dokuwiki-dumper/"

[project.scripts]
dokuWikiDumper = "dokuWikiDumper:main"
dokuWikiUploader = "dokuWikiUploader:main"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.2",
]

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["dokuWikiDumper", "dokuWikiUploader"]
module-root = ""

[tool.ruff]
line-length = 127

[tool.ruff.lint]
select = ["E9", "F63", "F7", "F82"]

[tool.ruff.lint.mccabe]
max-complexity = 10
