name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.14"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libxml2-dev libxslt-dev # for lxml
        uv sync --locked
    - name: Lint with Ruff
      run: |
        # exit if there are Python syntax errors or undefined names
        uv run ruff check .
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        uv run ruff check . --select E,F,W,C90 --exit-zero --statistics
    - name: run dokuWikiDumper
      run: |
        uv run python -m dokuWikiDumper -h
        uv run python -m dokuWikiUploader -h
    - name: Test with pytest
      run: |
        uv run pytest
